[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_INSTALL_CMD = "npm ci"
NIXPACKS_BUILD_CMD = "npm run build"
NIXPACKS_START_CMD = "npm start"
FORCE_NODE = "true"
NODE_ENV = "production"
